branch-defaults:
  main:
    environment: latest-londonbikeshare-env
    group_suffix: null
global:
  application_name: latest-londonbikeshare
  branch: null
  default_ec2_keyname: aws-latest-lb-demo
  default_platform: Python 3.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
